apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitops-frontend
  namespace: kitops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kitops-frontend
  template:
    metadata:
      labels:
        app: kitops-frontend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: frontend
        image: kitops/frontend:latest
        ports:
        - containerPort: 3000
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false  # Next.js may need write access
          capabilities:
            drop:
            - ALL
        env:
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: kitops-config
              key: API_URL
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: kitops-frontend
  namespace: kitops
spec:
  selector:
    app: kitops-frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP