# This file now uses External Secrets Operator or manual secret creation
# Secrets should be created from environment variables or external systems
# DO NOT commit hardcoded secrets to version control

# Example of how to create secrets from environment variables:
# kubectl create secret generic kitops-secrets \
#   --from-literal=DB_USERNAME="${DB_USERNAME}" \
#   --from-literal=DB_PASSWORD="${DB_PASSWORD}" \
#   --from-literal=JWT_SECRET="${JWT_SECRET}" \
#   --from-literal=STRIPE_SECRET_KEY="${STRIPE_SECRET_KEY}" \
#   --from-literal=OPENAI_API_KEY="${OPENAI_API_KEY}" \
#   --namespace=kitops

apiVersion: v1
kind: Secret
metadata:
  name: kitops-secrets
  namespace: kitops
type: Opaque
# Secrets will be populated by external systems or CI/CD
# This ensures no hardcoded secrets are stored in version control