apiVersion: v1
kind: Secret
metadata:
  name: kitops-secrets
  namespace: kitops
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  DB_USERNAME: a2l0b3Bz # kitops
  DB_PASSWORD: cGFzc3dvcmQ= # password
  JWT_SECRET: c3VwZXJfc2VjcmV0X2p3dF9rZXk= # super_secret_jwt_key
  STRIPE_SECRET_KEY: c2tfdGVzdF8xMjM0NTY3ODkw # sk_test_1234567890
  OPENAI_API_KEY: c2tfdGVzdF9vcGVuYWlfYXBpX2tleQ== # sk_test_openai_api_key